ahoyapi: v2
usage: CLI utilities
commands:

  satis:
    usage: Execute composer/satis via docker.
    cmd: |
      docker run --rm --init -it \
        --volume $(pwd):/build \
        --volume "${COMPOSER_HOME:-$HOME/.composer}:/composer" \
        composer/satis "$@"

  satis-build:
    usage: Execute composer/satis passing in a json and a build dir.
    cmd: |
      docker run --rm --init -it \
        --user $(id -u):$(id -g) \
        --volume $(pwd):/build \
        --volume "${COMPOSER_HOME:-$HOME/.composer}:/composer" \
        composer/satis build -vvv "$1" /build/"$2"
      docker run --rm --init -it \
        --volume $(pwd):/build \
        composer/satis /build/scripts/branding.sh "/build/$2"

  build:
    usage: Build everything in /app
    cmd: |
      ahoy build-stable
      ahoy build-master
      ahoy build-develop
      ahoy build-whitelist

  build-stable:
    usage: Build satis.govcms.gov.au
    cmd: |
      ahoy satis-build satis-config/govcms-stable.json app

  build-master:
    usage: Build satis.govcms.gov.au/master
    cmd: |
      ahoy satis-build satis-config/govcms-master.json app/master

  build-develop:
    usage: Build satis.govcms.gov.au/develop
    cmd: |
      ahoy satis-build satis-config/govcms-develop.json app/develop

  build-whitelist:
    usage: Build satis.govcms.gov.au/whitelist
    cmd: |
      ahoy satis-build satis-config/govcms-whitelist.json app/whitelist

  verify:
    usage: Locally run the same tests that would run in circle.
    cmd: |
      SATIS_BUILD=app ./verify.sh

  server:
    usage: Make satis available on localhost:4142
    cmd: |
      PHP -S localhost:4142 -t app
